### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by DairyWeb3638077** [Cog-Creators/Red-Dashboard#66]
### What part of dashboard are you having an issue with?

- [ ] Documentation
- [ X ] Dashboard webserver
- [ ] Dashboard cog

### What happened?

So I installed the dashboard from scratch and when I got down to the part where you have to start the dashboard via `reddash`, I get this error...
```md
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\reddashenv\Scripts\reddash.exe\__main__.py", line 4, in <module>
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\__main__.py", line 7, in <module>
    from reddash.app import create_app
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\app\__init__.py", line 8, in <module>
    from flask import Flask, url_for, session, render_template
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\Users\Owner\reddashenv\lib\site-packages\itsdangerous\__init__.py)
```

I have no clue why I get this error as I have installed the dashboard from scratch.
### What did you expect to happen?

The dashboard should have started.

### What can we do to reproduce this?

I have no clue.

### What is your bot/webserver running on?
- **Operating system**: 
- Windows
- **Python version**: 
- 3.9
- **Dashboard webserver version**:
- latest
- **Dashboard cog version**:
- latest

### What are you having issues on?
- **Operating system**: 
- Windows
- **Browser**:
- None Yet

**Comment by NeuroAssassin** [comment]
Fixed in 02acfc2.

**Comment by DairyWeb3638077** [comment]
Hey @NeuroAssassin For some reason, I am still getting the error when starting the dashboard. I uninstall the cog, installit again, delete the reddashenv folder, read it via the docs, run `reddash` and still get
```md
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\reddashenv\Scripts\reddash.exe\__main__.py", line 4, in <module>
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\__main__.py", line 7, in <module>
    from reddash.app import create_app
  File "C:\Users\Owner\reddashenv\lib\site-packages\reddash\app\__init__.py", line 8, in <module>
    from flask import Flask, url_for, session, render_template
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\Users\Owner\reddashenv\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\Users\Owner\reddashenv\lib\site-packages\itsdangerous\__init__.py)
```

**Comment by DairyWeb3638077** [comment]
Update, I am using Python 3.8.6

**Comment by DairyWeb3638077** [comment]
Just wondering, how long does it normally take to get published?

**Comment by NeuroAssassin** [comment]
It occurs when I believe there is enough substantial changes to warrant a version change.  Please redirect all other questions to a Discord server linked above, it is leaving the scope of this issue.
